/*
 * generated by Xtext 2.14.0
 */
package org


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TutorialStandaloneSetup extends TutorialStandaloneSetupGenerated {

	def static void doSetup() {
		new TutorialStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
