/**
 * generated by Xtext 2.14.0
 */
package org;

import org.AGESStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AGESStandaloneSetup extends AGESStandaloneSetupGenerated {
  public static void doSetup() {
    new AGESStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
