/**
 * generated by Xtext 2.14.0
 */
package org.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.AGESRuntimeModule;
import org.AGESStandaloneSetup;
import org.eclipse.xtext.util.Modules2;
import org.ide.AGESIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AGESIdeSetup extends AGESStandaloneSetup {
  @Override
  public Injector createInjector() {
    AGESRuntimeModule _aGESRuntimeModule = new AGESRuntimeModule();
    AGESIdeModule _aGESIdeModule = new AGESIdeModule();
    return Guice.createInjector(Modules2.mixin(_aGESRuntimeModule, _aGESIdeModule));
  }
}
