/**
 * generated by Xtext 2.14.0
 */
package org.ide;

import org.ide.AbstractAGESIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AGESIdeModule extends AbstractAGESIdeModule {
}
