/*
 * generated by Xtext 2.14.0
 */
package org.ui;

import com.google.inject.Injector;
import org.ages.ui.internal.AgesActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AGESExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(AgesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		AgesActivator activator = AgesActivator.getInstance();
		return activator != null ? activator.getInjector(AgesActivator.ORG_AGES) : null;
	}

}
