/*
 * generated by Xtext 2.14.0
 */
package org.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTutorialScopeProvider extends DelegatingScopeProvider {
}
