/*
 * generated by Xtext 2.14.0
 */
package org.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.parser.antlr.internal.InternalAGESParser;
import org.services.AGESGrammarAccess;

public class AGESParser extends AbstractAntlrParser {

	@Inject
	private AGESGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAGESParser createParser(XtextTokenStream stream) {
		return new InternalAGESParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public AGESGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AGESGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
