/**
 * generated by Xtext 2.14.0
 */
package org.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.TutorialRuntimeModule;
import org.TutorialStandaloneSetup;
import org.eclipse.xtext.util.Modules2;
import org.ide.TutorialIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TutorialIdeSetup extends TutorialStandaloneSetup {
  @Override
  public Injector createInjector() {
    TutorialRuntimeModule _tutorialRuntimeModule = new TutorialRuntimeModule();
    TutorialIdeModule _tutorialIdeModule = new TutorialIdeModule();
    return Guice.createInjector(Modules2.mixin(_tutorialRuntimeModule, _tutorialIdeModule));
  }
}
