/*
 * generated by Xtext 2.14.0
 */
package org.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import tutorial.ui.internal.TutorialActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TutorialExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TutorialActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TutorialActivator activator = TutorialActivator.getInstance();
		return activator != null ? activator.getInjector(TutorialActivator.ORG_TUTORIAL) : null;
	}

}
