/*
 * generated by Xtext 2.14.0
 */
package org.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.tutorial.Domainmodel

@RunWith(XtextRunner)
@InjectWith(TutorialInjectorProvider)
class TutorialParsingTest {
	@Inject
	ParseHelper<Domainmodel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			datatype String
			datatype Int
			
			entity Aluno {
				name: String
				age: Int
				matricula: Int
			}
			
			entity Escola {
				name: String
				address: String
			}
			
			entity Materia {
				name: String
				id: Int
			}
			
			
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
