/**
 * generated by Xtext 2.14.0
 */
package org;

import org.AbstractTutorialRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TutorialRuntimeModule extends AbstractTutorialRuntimeModule {
}
