/**
 * generated by Xtext 2.14.0
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.ui.AbstractTutorialUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TutorialUiModule extends AbstractTutorialUiModule {
  public TutorialUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
