/*
 * generated by Xtext 2.14.0
 */
package org.ui.tests;

import com.google.inject.Injector;
import org.ages.ui.internal.AgesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AGESUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AgesActivator.getInstance().getInjector("org.AGES");
	}

}
