/**
 * generated by Xtext 2.14.0
 */
package org.tutorial;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.tutorial.TutorialPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
